// Bundled countries + states data — replaces the countriesnow.space external API call.
// Format mirrors the countriesnow.space response so checkout.js needs minimal changes:
//   { name: string, states: Array<{ name: string }> }
// Countries without a states list degrade to a free-text state input in checkout.

const s = (names) => names.map((n) => ({ name: n }));

export const GEO_DATA = [
  // ── Africa ──────────────────────────────────────────────────────────────────
  {
    name: 'Nigeria',
    states: s([
      'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
      'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
      'FCT (Abuja)', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina',
      'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo',
      'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
    ]),
  },
  {
    name: 'Ghana',
    states: s([
      'Ahafo', 'Ashanti', 'Bono', 'Bono East', 'Central', 'Eastern',
      'Greater Accra', 'North East', 'Northern', 'Oti', 'Savannah',
      'Upper East', 'Upper West', 'Volta', 'Western', 'Western North',
    ]),
  },
  {
    name: 'Kenya',
    states: s([
      'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu',
      'Garissa', 'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho',
      'Kiambu', 'Kilifi', 'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale',
      'Laikipia', 'Lamu', 'Machakos', 'Makueni', 'Mandera', 'Marsabit',
      'Meru', "Migori", 'Mombasa', "Murang'a", 'Nairobi', 'Nakuru', 'Nandi',
      'Narok', 'Nyamira', 'Nyandarua', 'Nyeri', 'Samburu', 'Siaya',
      'Taita-Taveta', 'Tana River', 'Tharaka-Nithi', 'Trans Nzoia', 'Turkana',
      'Uasin Gishu', 'Vihiga', 'Wajir', 'West Pokot',
    ]),
  },
  {
    name: 'South Africa',
    states: s([
      'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
      'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape',
    ]),
  },
  {
    name: 'Ethiopia',
    states: s([
      'Addis Ababa', 'Afar', 'Amhara', 'Benishangul-Gumuz', 'Dire Dawa',
      'Gambela', 'Harari', 'Oromia', 'Sidama', 'Somali',
      'South West Ethiopia Peoples', 'Southern Nations Nationalities',
      'Tigray',
    ]),
  },
  {
    name: 'Tanzania',
    states: s([
      'Arusha', 'Dar es Salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera',
      'Katavi', 'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara',
      'Mbeya', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pemba North',
      'Pemba South', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu',
      'Singida', 'Songwe', 'Tabora', 'Tanga', 'Unguja North', 'Unguja South',
      'Zanzibar West',
    ]),
  },
  {
    name: 'Uganda',
    states: s([
      'Buganda', 'Busoga', 'Central', 'Eastern', 'Kampala', 'Northern',
      'Western',
    ]),
  },
  {
    name: 'Cameroon',
    states: s([
      'Adamawa', 'Centre', 'East', 'Far North', 'Littoral', 'North',
      'North West', 'South', 'South West', 'West',
    ]),
  },
  {
    name: 'Senegal',
    states: s([
      'Dakar', 'Diourbel', 'Fatick', 'Kaffrine', 'Kaolack', 'Kédougou',
      'Kolda', 'Louga', 'Matam', 'Saint-Louis', 'Sédhiou', 'Tambacounda',
      'Thiès', 'Ziguinchor',
    ]),
  },
  {
    name: 'Côte d\'Ivoire',
    states: s([
      'Abidjan', 'Bas-Sassandra', 'Comoé', 'Denguélé', 'Gôh-Djiboua',
      'Lacs', 'Lagunes', 'Montagnes', 'Sassandra-Marahoué', 'Savanes',
      'Vallée du Bandama', 'Woroba', 'Yamoussoukro', 'Zanzan',
    ]),
  },

  // ── Americas ─────────────────────────────────────────────────────────────
  {
    name: 'United States',
    states: s([
      'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
      'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
      'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
      'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
      'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
      'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina',
      'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
      'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas',
      'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
      'Wisconsin', 'Wyoming',
    ]),
  },
  {
    name: 'Canada',
    states: s([
      'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
      'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia',
      'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan',
      'Yukon',
    ]),
  },
  {
    name: 'Brazil',
    states: s([
      'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará',
      'Distrito Federal', 'Espírito Santo', 'Goiás', 'Maranhão',
      'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará', 'Paraíba',
      'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro', 'Rio Grande do Norte',
      'Rio Grande do Sul', 'Rondônia', 'Roraima', 'Santa Catarina',
      'São Paulo', 'Sergipe', 'Tocantins',
    ]),
  },
  {
    name: 'Mexico',
    states: s([
      'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche',
      'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'Durango', 'Guanajuato',
      'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico City', 'Mexico State',
      'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla',
      'Querétaro', 'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora',
      'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas',
    ]),
  },
  { name: 'Argentina', states: s(['Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes', 'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego', 'Tucumán']) },
  { name: 'Colombia', states: s(['Amazonas', 'Antioquia', 'Arauca', 'Atlántico', 'Bolívar', 'Boyacá', 'Caldas', 'Caquetá', 'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Córdoba', 'Cundinamarca', 'Guainía', 'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño', 'Norte de Santander', 'Putumayo', 'Quindío', 'Risaralda', 'San Andrés', 'Santander', 'Sucre', 'Tolima', 'Valle del Cauca', 'Vaupés', 'Vichada']) },

  // ── Europe ───────────────────────────────────────────────────────────────
  {
    name: 'United Kingdom',
    states: s(['England', 'Northern Ireland', 'Scotland', 'Wales']),
  },
  {
    name: 'Germany',
    states: s([
      'Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen',
      'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern',
      'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland', 'Saxony',
      'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia',
    ]),
  },
  {
    name: 'France',
    states: s([
      'Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Brittany',
      'Centre-Val de Loire', 'Corsica', 'Grand Est', 'Hauts-de-France',
      'Île-de-France', 'Normandy', 'Nouvelle-Aquitaine', 'Occitanie',
      'Pays de la Loire', "Provence-Alpes-Côte d'Azur",
    ]),
  },
  { name: 'Italy', states: s(['Abruzzo', 'Aosta Valley', 'Apulia', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardy', 'Marche', 'Molise', 'Piedmont', 'Sardinia', 'Sicily', 'Trentino-South Tyrol', 'Tuscany', 'Umbria', 'Veneto']) },
  { name: 'Spain', states: s(['Andalusia', 'Aragon', 'Asturias', 'Balearic Islands', 'Basque Country', 'Canary Islands', 'Cantabria', 'Castile and León', 'Castile-La Mancha', 'Catalonia', 'Ceuta', 'Community of Madrid', 'Extremadura', 'Galicia', 'La Rioja', 'Melilla', 'Murcia', 'Navarre', 'Valencia']) },
  { name: 'Netherlands', states: s(['Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen', 'Limburg', 'North Brabant', 'North Holland', 'Overijssel', 'South Holland', 'Utrecht', 'Zeeland']) },

  // ── Middle East ──────────────────────────────────────────────────────────
  {
    name: 'United Arab Emirates',
    states: s(['Abu Dhabi', 'Ajman', 'Dubai', 'Fujairah', 'Ras Al Khaimah', 'Sharjah', 'Umm Al Quwain']),
  },
  { name: 'Saudi Arabia', states: s(['Al Bahah', 'Al Jawf', 'Al Madinah', 'Al Qasim', "Ar Riyad", 'Asir', "Ha'il", 'Jazan', 'Makkah', 'Najran', 'Northern Borders', 'Tabuk', 'Eastern Province']) },
  { name: 'Qatar', states: s(['Ad Dawhah', 'Al Khawr', 'Al Shahaniya', 'Al Wakrah', 'Ar Rayyan', 'Ash Shamal', 'Az Zubarah', 'Madinat ash Shamal', 'Umm Salal']) },

  // ── Asia ─────────────────────────────────────────────────────────────────
  {
    name: 'India',
    states: s([
      'Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh',
      'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
      'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Goa', 'Gujarat',
      'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
      'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh',
      'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
      'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
      'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    ]),
  },
  {
    name: 'China',
    states: s([
      'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong',
      'Guangxi', 'Guizhou', 'Hainan', 'Hebei', 'Heilongjiang', 'Henan',
      'Hong Kong', 'Hubei', 'Hunan', 'Inner Mongolia', 'Jiangsu', 'Jiangxi',
      'Jilin', 'Liaoning', 'Macau', 'Ningxia', 'Qinghai', 'Shaanxi',
      'Shandong', 'Shanghai', 'Shanxi', 'Sichuan', 'Tianjin', 'Tibet',
      'Xinjiang', 'Yunnan', 'Zhejiang',
    ]),
  },
  {
    name: 'Australia',
    states: s([
      'Australian Capital Territory', 'New South Wales', 'Northern Territory',
      'Queensland', 'South Australia', 'Tasmania', 'Victoria',
      'Western Australia',
    ]),
  },

  // ── Rest of world (no state list — falls back to text input) ─────────────
  { name: 'Afghanistan', states: [] },
  { name: 'Albania', states: [] },
  { name: 'Algeria', states: [] },
  { name: 'Andorra', states: [] },
  { name: 'Angola', states: [] },
  { name: 'Antigua and Barbuda', states: [] },
  { name: 'Armenia', states: [] },
  { name: 'Austria', states: [] },
  { name: 'Azerbaijan', states: [] },
  { name: 'Bahamas', states: [] },
  { name: 'Bahrain', states: [] },
  { name: 'Bangladesh', states: [] },
  { name: 'Barbados', states: [] },
  { name: 'Belarus', states: [] },
  { name: 'Belgium', states: [] },
  { name: 'Belize', states: [] },
  { name: 'Benin', states: [] },
  { name: 'Bhutan', states: [] },
  { name: 'Bolivia', states: [] },
  { name: 'Bosnia and Herzegovina', states: [] },
  { name: 'Botswana', states: [] },
  { name: 'Brunei', states: [] },
  { name: 'Bulgaria', states: [] },
  { name: 'Burkina Faso', states: [] },
  { name: 'Burundi', states: [] },
  { name: 'Cabo Verde', states: [] },
  { name: 'Cambodia', states: [] },
  { name: 'Central African Republic', states: [] },
  { name: 'Chad', states: [] },
  { name: 'Chile', states: [] },
  { name: 'Comoros', states: [] },
  { name: 'Congo', states: [] },
  { name: 'Democratic Republic of the Congo', states: [] },
  { name: 'Costa Rica', states: [] },
  { name: 'Croatia', states: [] },
  { name: 'Cuba', states: [] },
  { name: 'Cyprus', states: [] },
  { name: 'Czech Republic', states: [] },
  { name: 'Denmark', states: [] },
  { name: 'Djibouti', states: [] },
  { name: 'Dominica', states: [] },
  { name: 'Dominican Republic', states: [] },
  { name: 'Ecuador', states: [] },
  { name: 'Egypt', states: [] },
  { name: 'El Salvador', states: [] },
  { name: 'Equatorial Guinea', states: [] },
  { name: 'Eritrea', states: [] },
  { name: 'Estonia', states: [] },
  { name: 'Eswatini', states: [] },
  { name: 'Fiji', states: [] },
  { name: 'Finland', states: [] },
  { name: 'Gabon', states: [] },
  { name: 'Gambia', states: [] },
  { name: 'Georgia', states: [] },
  { name: 'Greece', states: [] },
  { name: 'Grenada', states: [] },
  { name: 'Guatemala', states: [] },
  { name: 'Guinea', states: [] },
  { name: 'Guinea-Bissau', states: [] },
  { name: 'Guyana', states: [] },
  { name: 'Haiti', states: [] },
  { name: 'Honduras', states: [] },
  { name: 'Hungary', states: [] },
  { name: 'Iceland', states: [] },
  { name: 'Indonesia', states: [] },
  { name: 'Iran', states: [] },
  { name: 'Iraq', states: [] },
  { name: 'Ireland', states: [] },
  { name: 'Israel', states: [] },
  { name: 'Jamaica', states: [] },
  { name: 'Japan', states: [] },
  { name: 'Jordan', states: [] },
  { name: 'Kazakhstan', states: [] },
  { name: 'Kiribati', states: [] },
  { name: 'Kuwait', states: [] },
  { name: 'Kyrgyzstan', states: [] },
  { name: 'Laos', states: [] },
  { name: 'Latvia', states: [] },
  { name: 'Lebanon', states: [] },
  { name: 'Lesotho', states: [] },
  { name: 'Liberia', states: [] },
  { name: 'Libya', states: [] },
  { name: 'Liechtenstein', states: [] },
  { name: 'Lithuania', states: [] },
  { name: 'Luxembourg', states: [] },
  { name: 'Madagascar', states: [] },
  { name: 'Malawi', states: [] },
  { name: 'Malaysia', states: [] },
  { name: 'Maldives', states: [] },
  { name: 'Mali', states: [] },
  { name: 'Malta', states: [] },
  { name: 'Marshall Islands', states: [] },
  { name: 'Mauritania', states: [] },
  { name: 'Mauritius', states: [] },
  { name: 'Micronesia', states: [] },
  { name: 'Moldova', states: [] },
  { name: 'Monaco', states: [] },
  { name: 'Mongolia', states: [] },
  { name: 'Montenegro', states: [] },
  { name: 'Morocco', states: [] },
  { name: 'Mozambique', states: [] },
  { name: 'Myanmar', states: [] },
  { name: 'Namibia', states: [] },
  { name: 'Nauru', states: [] },
  { name: 'Nepal', states: [] },
  { name: 'New Zealand', states: [] },
  { name: 'Nicaragua', states: [] },
  { name: 'Niger', states: [] },
  { name: 'North Korea', states: [] },
  { name: 'North Macedonia', states: [] },
  { name: 'Norway', states: [] },
  { name: 'Oman', states: [] },
  { name: 'Pakistan', states: [] },
  { name: 'Palau', states: [] },
  { name: 'Palestine', states: [] },
  { name: 'Panama', states: [] },
  { name: 'Papua New Guinea', states: [] },
  { name: 'Paraguay', states: [] },
  { name: 'Peru', states: [] },
  { name: 'Philippines', states: [] },
  { name: 'Poland', states: [] },
  { name: 'Portugal', states: [] },
  { name: 'Romania', states: [] },
  { name: 'Russia', states: [] },
  { name: 'Rwanda', states: [] },
  { name: 'Saint Kitts and Nevis', states: [] },
  { name: 'Saint Lucia', states: [] },
  { name: 'Saint Vincent and the Grenadines', states: [] },
  { name: 'Samoa', states: [] },
  { name: 'San Marino', states: [] },
  { name: 'Sao Tome and Principe', states: [] },
  { name: 'Serbia', states: [] },
  { name: 'Seychelles', states: [] },
  { name: 'Sierra Leone', states: [] },
  { name: 'Singapore', states: [] },
  { name: 'Slovakia', states: [] },
  { name: 'Slovenia', states: [] },
  { name: 'Solomon Islands', states: [] },
  { name: 'Somalia', states: [] },
  { name: 'South Korea', states: [] },
  { name: 'South Sudan', states: [] },
  { name: 'Sri Lanka', states: [] },
  { name: 'Sudan', states: [] },
  { name: 'Suriname', states: [] },
  { name: 'Sweden', states: [] },
  { name: 'Switzerland', states: [] },
  { name: 'Syria', states: [] },
  { name: 'Taiwan', states: [] },
  { name: 'Tajikistan', states: [] },
  { name: 'Thailand', states: [] },
  { name: 'Timor-Leste', states: [] },
  { name: 'Togo', states: [] },
  { name: 'Tonga', states: [] },
  { name: 'Trinidad and Tobago', states: [] },
  { name: 'Tunisia', states: [] },
  { name: 'Turkey', states: [] },
  { name: 'Turkmenistan', states: [] },
  { name: 'Tuvalu', states: [] },
  { name: 'Ukraine', states: [] },
  { name: 'Uruguay', states: [] },
  { name: 'Uzbekistan', states: [] },
  { name: 'Vanuatu', states: [] },
  { name: 'Vatican City', states: [] },
  { name: 'Venezuela', states: [] },
  { name: 'Vietnam', states: [] },
  { name: 'Yemen', states: [] },
  { name: 'Zambia', states: [] },
  { name: 'Zimbabwe', states: [] },
];
